# Advanced Classification Predict

© Explore Data Science Academy

## Honour Code

I **YOUR NAME**, confirm - by submitting this document - that the solutions in this notebook are a result of my own work and that I abide by the EDSA honour code (https://drive.google.com/file/d/1QDCjGZJ8-FmJE3bZdIQNwnJyQKPhHZBn/view?usp=sharing).

Non-compliance with the honour code constitutes a material breach of contract.

### Import Libraries and Read In the Data

Do not modify or remove any of the code in these cells.

In [77]:
!pip install imbalanced-learn
!pip install -U imbalanced-learn
!pip install sklearn.metrics
from IPython.display import Image
from IPython.display import IFrame
from IPython import display
import pandas as pd
import numpy as np

import nltk
import sklearn
import imblearn
import csv
%matplotlib inline

from nltk import TreebankWordTokenizer, SnowballStemmer
from nltk.tokenize import TweetTokenizer
from nltk.tokenize import  word_tokenize
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords

from imblearn.metrics import classification_report_imbalanced

from sklearn.preprocessing import LabelBinarizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import VarianceThreshold

from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix

import string
import urllib
import math
import re

nltk.download('wordnet')
nltk.download('stopwords')

ERROR: Could not find a version that satisfies the requirement sklearn.metrics
ERROR: No matching distribution found for sklearn.metrics
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\5970\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\5970\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [78]:
train  = pd.read_csv('train.csv')
test = pd.read_csv('test.csv') # no labels

train.head()

sentiment                                            message  tweetid
0          1  PolySciMajor EPA chief doesn't think carbon di...   625221
1          1  It's not like we lack evidence of anthropogeni...   126103
2          2  RT @RawStory: Researchers say we have three ye...   698562
3          1  #TodayinMaker# WIRED : 2016 was a pivotal year...   573736
4          1  RT @SoyNovioDeTodas: It's 2016, and a racist, ...   466954

In [79]:
test.head()

message  tweetid
0  Europe will now be looking to China to make su...   169760
1  Combine this with the polling of staffers re c...    35326
2  The scary, unimpeachable evidence that climate...   224985
3  @Karoli @morgfair @OsborneInk @dailykos \nPuti...   476263
4  RT @FakeWillMoore: 'Female orgasms cause globa...   872928

## Overview

Refer to this diagram to guide you while you build your model. Some of the steps will be fleshed out in this template.

![Overview](process_overview_final.jpg)

## Basic preprocessing

Here is a template you may use for your initial base model. 

### Removing URL's
Write a function that removes URL's from a single tweet. 

**Function input:**
- A single string object (tweet) 

**Function output:**
- The tweet with URL's removed as a single object

In [80]:
# define function that removes URL from single tweet
def remove_urls(text):
    pattern_url = r'http[s]?://(?:[A-Za-z]|[0-9]|[$-_@.&+]|[!*\(\),]|(?:%[0-9A-Fa-f][0-9A-Fa-f]))+\s'
    subs_url = r'url-web'
    text = train['message'].replace(to_replace = pattern_url, value = subs_url, regex = True)
    return text

**Original object:**

In [81]:
tweet = train['message'][2]
tweet

'RT @RawStory: Researchers say we have three years to act on climate change before it’s too late https://t.co/WdT0KdUr2f https://t.co/Z0ANPT…'

In [82]:
remove_urls(tweet)

0        PolySciMajor EPA chief doesn't think carbon di...
1        It's not like we lack evidence of anthropogeni...
2        RT @RawStory: Researchers say we have three ye...
3        #TodayinMaker# WIRED : 2016 was a pivotal year...
4        RT @SoyNovioDeTodas: It's 2016, and a racist, ...
                               ...                        
15814    RT @ezlusztig: They took down the material on ...
15815    RT @washingtonpost: How climate change could b...
15816    notiven: RT: nytimesworld :What does Trump act...
15817    RT @sara8smiles: Hey liberals the climate chan...
15818    RT @Chet_Cannon: .@kurteichenwald's 'climate c...
Name: message, Length: 15819, dtype: object

**Expected output:**
```python
remove_urls(tweet)

>>'RT @RawStory: Researchers say we have three years to act on climate change before it’s too late  '
```

### Convert to lowercase

Write a function that converts a single tweet to lowercase.

**Function input:**
- A single string object (tweet) 

**Function output:**
- The tweet in lowercase as a single object

In [83]:
def to_lower(text):
    # YOUR CODE HERE 
    return

**Original object:**

In [84]:
tweet

'RT @RawStory: Researchers say we have three years to act on climate change before it’s too late https://t.co/WdT0KdUr2f https://t.co/Z0ANPT…'

In [85]:
to_lower(tweet)

**Expected output:**

```python 
to_lower(tweet)
>> 'rt @rawstory: researchers say we have three years to act on climate change before it’s too late https://t.co/wdt0kdur2f https://t.co/z0anpt…'
```

### Stemming or lemmatising

Write a function that derives the root words for each of the words in a tweet. You may use stemming _or_ lemmatising here.

**Function input:**
- A single string object (tweet) 

**Function output:**
- The tweet in root words as a _single_ object

In [86]:
def get_roots(text):
    # YOUR CODE HERE 
    return

**Original object:**

In [87]:
tweet

'RT @RawStory: Researchers say we have three years to act on climate change before it’s too late https://t.co/WdT0KdUr2f https://t.co/Z0ANPT…'

**Expected output:**
```python
get_roots(tweet)
```
Using `SnowballStemmer()`
```python
>> 'rt @rawstory: research say we have three year to act on climat chang befor it too late https://t.co/wdt0kdur2f https://t.co/z0anpt…'
```

Using `WordNetLemmatizer()`
```python
>> 'RT @RawStory: Researchers say we have three years to act on climate change before it’s too late https://t.co/WdT0KdUr2f https://t.co/Z0ANPT…'
```

### Other preprocessing techniques 

Come back here once you have submitted your base model to add any other preprocessing functions yuo wish to add

In [88]:
# YOUR CODE HERE
train.info()





<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15819 entries, 0 to 15818
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   sentiment  15819 non-null  int64 
 1   message    15819 non-null  object
 2   tweetid    15819 non-null  int64 
dtypes: int64(2), object(1)
memory usage: 370.9+ KB


### Tokenising 

Write a function that tokenises a single tweet into a list of tokens.

**Function input:**
- A single string object (tweet) 

**Function output:**
- A list of tokens (objects).

In [89]:
def get_tokens(text):
    # YOUR CODE HERE 
    return 

**Original object:**

In [90]:
tweet

'RT @RawStory: Researchers say we have three years to act on climate change before it’s too late https://t.co/WdT0KdUr2f https://t.co/Z0ANPT…'

In [91]:
get_tokens(tweet)

**Expected output:**
```python
get_tokens(tweet)

>> ['RT',
 '@',
 'RawStory',
 ':',
 'Researchers',
 'say',
 'we',
 'have',
 'three',
 'years',
 'to',
 'act',
 'on',
 'climate',
 'change',
 'before',
 'it’s',
 'too',
 'late',
 'https',
 ':',
 '//t.co/WdT0KdUr2f',
 'https',
 ':',
 '//t.co/Z0ANPT…']
```

Besides the preprocessing methods we've already discussed, can you think of how our data can be improved at this stage?

### Vectorising 

Use the code from the webinar to define your vecotiser. For more details on this function have a look at the `sklearn`
<a href="https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html">package documentation on the function</a>. Recall that this function, unlike the others before takes an _**entire column**_ as an argument.

### Putting all the functions together 

Test your cleaning functions on a single tweet. Perform the cleaning procedure on this tweet from start to finish. Make sure the output looks as you would expect. Store the cleaned tweet in `tweet_final`. Don't worry about vectorising for now.

**_Include any other cleaning procedures you add after your base model_**

**Original object:**

In [92]:
tweet

'RT @RawStory: Researchers say we have three years to act on climate change before it’s too late https://t.co/WdT0KdUr2f https://t.co/Z0ANPT…'

In [93]:
stemmer = SnowballStemmer("english")

In [94]:
def remove_punctuation(post):
    return ''.join([l for l in post if l not in string.punctuation])

In [95]:
train['message'] = train['message'].apply(remove_punctuation)
train['message'].iloc[15818]

'RT ChetCannon kurteichenwalds climate change equation in 4 screenshots httpstcolp7UufcxDQ'

In [96]:
tweet = train['message'][2]

In [97]:
from sklearn.feature_extraction.text import CountVectorizer

In [98]:
# clean tweet from start to finish
tweet1 = remove_urls(tweet)
tweet2 = ''.join([l for l in str(tweet1) if l not in string.punctuation])
tweet3 = tweet2.lower()
#tweet1 = re.sub(r'RT[\s]+', '',tweet1)
tokens = re.split('\W+', str(tweet3))


tweet4 = [stemmer.stem(word) for word in tokens]

tweet_final = tweet4

# cleaned tweet
#tweet_final= CountVectorizer(stop_words='english')

In [99]:
#Test data
tweets = test['message']
tweets1 = remove_urls(tweets)
tweets2 = ''.join([l for l in str(tweets1) if l not in string.punctuation])
tweets3 = tweets2.lower()
#tweet1 = re.sub(r'RT[\s]+', '',tweet1)
tokenss = re.split('\W+', str(tweets3))


tweets4 = [stemmer.stem(word) for word in tokenss]

tweets_final = tweets4

In [100]:
tweet4

['0',
 'polyscimajor',
 'epa',
 'chief',
 'doesnt',
 'think',
 'carbon',
 'dio',
 '1',
 'it',
 'not',
 'like',
 'we',
 'lack',
 'evid',
 'of',
 'anthropogen',
 '2',
 'rt',
 'rawstori',
 'research',
 'say',
 'we',
 'have',
 'three',
 'year',
 '3',
 'todayinmak',
 'wire',
 '2016',
 'was',
 'a',
 'pivot',
 'year',
 'in',
 '4',
 'rt',
 'soynoviodetoda',
 'it',
 '2016',
 'and',
 'a',
 'racist',
 'sexi',
 '15814',
 'rt',
 'ezlusztig',
 'they',
 'took',
 'down',
 'the',
 'materi',
 'on',
 'gl',
 '15815',
 'rt',
 'washingtonpost',
 'how',
 'climat',
 'chang',
 'could',
 'be',
 '15816',
 'notiven',
 'rt',
 'nytimesworld',
 'what',
 'doe',
 'trump',
 'actual',
 '15817',
 'rt',
 'sara8smil',
 'hey',
 'liber',
 'the',
 'climat',
 'chang',
 '15818',
 'rt',
 'chetcannon',
 'kurteichenwald',
 'climat',
 'chang',
 'e',
 'name',
 'messag',
 'length',
 '15819',
 'dtype',
 'object']

In [101]:
#train['message_clean'] = tweet4

**Expected output:**
```python
tweet_final
>>['rt',
 '@',
 'rawstory',
 ':',
 'research',
 'say',
 'we',
 'have',
 'three',
 'year',
 'to',
 'act',
 'on',
 'climat',
 'chang',
 'befor',
 'it',
 'too',
 'late']
```

### Preprocessing and cleaning entire column of tweets

Now that we know how to clean a single tweet, we can use `apply()` to clean the entire column in the dataframe. This is what the column looks like to begin with.

In [102]:
train['message'].head()

0    PolySciMajor EPA chief doesnt think carbon dio...
1    Its not like we lack evidence of anthropogenic...
2    RT RawStory Researchers say we have three year...
3    TodayinMaker WIRED  2016 was a pivotal year in...
4    RT SoyNovioDeTodas Its 2016 and a racist sexis...
Name: message, dtype: object

In [103]:
!pip install textblob

In [104]:
from textblob import TextBlob, Word, Blobber
from textblob.classifiers import NaiveBayesClassifier
from textblob.taggers import NLTKTagger

In [105]:
def getSubjectivity(text):
    return TextBlob(text).sentiment.subjectivity

In [106]:
def getPolarity(text):
    return TextBlob(text).sentiment.polarity

In [107]:
#train['subjectivity']= train['message'].apply(getSubjectivity)
#train['polarity']= train['message'].apply(getPolarity)

In [108]:
train.head()

sentiment                                            message  tweetid
0          1  PolySciMajor EPA chief doesnt think carbon dio...   625221
1          1  Its not like we lack evidence of anthropogenic...   126103
2          2  RT RawStory Researchers say we have three year...   698562
3          1  TodayinMaker WIRED  2016 was a pivotal year in...   573736
4          1  RT SoyNovioDeTodas Its 2016 and a racist sexis...   466954

Write code that applies your cleaning functions to the entire `message` column of the dataframe using `.apply()`. Do not vectorise just yet. Store this in a new column, `train['message_clean']`. 

In [109]:
# applying cleaning functions to entire column of dataframe (NO VECTORISING)


# YOUR CODE HERE - use apply with all your cleaning functions 

#train['message_clean'] = vect

#train['message_clean']

### Vectorising 

Vectorise your cleaned data using the vectoriser you defined earlier. Don't forget to fit the vectoriser to the data you just cleaned. Store your vectorised data in `train_vec`.

In [110]:
# vectorise your cleaned data
vect = CountVectorizer()
vect.fit(tweet_final)
vect.fit(tweets_final)
#betterVect.fit(train['message'])
# YOUR CODE HERE 

CountVectorizer()

In [111]:
corpus = train['message']
corpuss = test['message']

In [112]:
X = vect.fit(corpus)
X_tee = vect.fit(corpuss)

In [113]:
print (X.vocabulary_)

{'europe': 7715, 'will': 22933, 'now': 15030, 'be': 3013, 'looking': 13068, 'to': 21122, 'china': 4518, 'make': 13359, 'sure': 20272, 'that': 20733, 'it': 11217, 'is': 11167, 'not': 15000, 'alone': 2003, 'in': 10785, 'fighting': 8260, 'climate': 4753, 'change': 4401, 'https': 10304, 'co': 4917, 'o7t8rcgwdq': 15212, 'combine': 5014, 'this': 20924, 'with': 23005, 'the': 20745, 'polling': 16495, 'of': 15324, 'staffers': 19846, 're': 17489, 'and': 2153, 'womens': 23076, 'rights': 18074, 'you': 23677, 'have': 9815, 'fascist': 8086, 'state': 19901, 'ifrm7eexpj': 10593, 'scary': 18691, 'unimpeachable': 21855, 'evidence': 7756, 'already': 2008, 'here': 9964, 'yaedqcv9ki': 23527, 'itstimetochange': 11243, 'climatechange': 4765, 'zeroco2_': 23895, 'karoli': 12014, 'morgfair': 14231, 'osborneink': 15562, 'dailykos': 5796, 'putin': 17026, 'got': 9297, 'too': 21186, 'jill': 11586, 'trump': 21410, 'doesn': 6699, 'believe': 3100, 'at': 2571, 'all': 1972, 'thinks': 20916, 'hoax': 10130, 'rt': 18316, '

In [114]:
print (vect.get_feature_names())

['000', '000058', '00pm', '01', '02hjfphzix', '02jbu2udyy', '039strch8n', '04', '04vmhuj4ko', '060x2hcwm2', '061tlkza0x', '068wrr4gui', '06ynhjal2i', '07', '07am', '07e5bdcy4p', '07hzxozi4r', '08', '080yqpw1ng', '094', '09ocsab4b1', '09tnb97rrv', '0a3jod6lmh', '0aalaqjyg3', '0advg1wgly', '0amv4ttalj', '0ax53a05q4', '0bama', '0begddodfi', '0bjgbngdtt', '0blydqnbbn', '0c3bbsi0h1', '0c80q9aqdl', '0cmjlqrzgi', '0css4pherl', '0d02chtyek', '0dbjikotnm', '0dcezgrab0', '0dkakdqnp8', '0dkqagdwto', '0dn1oarwei', '0dnwcydcbv', '0ehmwmz3ve', '0f7cu920cu', '0fgkhyy67e', '0fijxfl07t', '0fuykfmb1z', '0fvqjdmipg', '0gwq8maitv', '0hbkwyshve', '0hfqzodx0g', '0i572oeaxg', '0i71v4bapl', '0irw3utxnk', '0jphxqgoyp', '0kikpioqkk', '0kkoym6cyw', '0kqhutei3u', '0kthr50aou', '0kunioo68v', '0ln1kln2et', '0lwrem2k8k', '0mclvjal5m', '0n5qmab0jv', '0nd3l2ozxn', '0ngy8dgr8p', '0p', '0pb7w38git', '0psaslh9p1', '0pvjhrvv1j', '0pzzv4gkzl', '0qbzmwfq59', '0qiksh', '0qpfvefjoe', '0qvm7h78ba', '0qzs4nzvud', '0rivzc3tqx', 

C:\Users\5970\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [115]:
X = vect.transform(corpus)
Xs = vect.transform(corpuss)

In [116]:
print (X.shape)

(15819, 24149)


In [117]:
print (X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [118]:
xx= pd.DataFrame (X.toarray(), columns = vect.get_feature_names())
xxs = pd.DataFrame (Xs.toarray(), columns = vect.get_feature_names())

In [119]:
xx

000  000058  00pm  01  02hjfphzix  02jbu2udyy  039strch8n  04  \
0        0       0     0   0           0           0           0   0   
1        0       0     0   0           0           0           0   0   
2        0       0     0   0           0           0           0   0   
3        0       0     0   0           0           0           0   0   
4        0       0     0   0           0           0           0   0   
...    ...     ...   ...  ..         ...         ...         ...  ..   
15814    0       0     0   0           0           0           0   0   
15815    0       0     0   0           0           0           0   0   
15816    0       0     0   0           0           0           0   0   
15817    0       0     0   0           0           0           0   0   
15818    0       0     0   0           0           0           0   0   

       04vmhuj4ko  060x2hcwm2  ...  ให  ไปรยาก  オゾン層  ㅤㅤㅤㅤㅤㅤglobal  ㅤㅤㅤㅤㅤㅤㅤㅤㅤ  \
0               0           0  ...   0       0     0             0          0   
1               0           0  ...   0       0     0             0          0   
2               0           0  ...   0       0     0             0          0   
3               0           0  ...   0       0     0             0          0   
4               0           0  ...   0       0     0             0          0   
...           ...         ...  ...  ..     ...   ...           ...        ...   
15814           0           0  ...   0       0     0             0          0   
15815           0           0  ...   0       0     0             0          0   
15816           0           0  ...   0       0     0             0          0   
15817           0           0  ...   0       0     0             0          0   
15818           0           0  ...   0       0     0             0          0   

       京都議定書  地球温暖化  温室効果  環境がテーマの文章ででやすい単語２  皮膚ガン  
0          0      0     0                  0     0  
1          0      0     0                  0     0  
2          0      0     0                  0     0  
3          0      0     0                  0     0  
4          0      0     0                  0     0  
...      ...    ...   ...                ...   ...  
15814      0      0     0                  0     0  
15815      0      0     0                  0     0  
15816      0      0     0                  0     0  
15817      0      0     0                  0     0  
15818      0      0     0                  0     0  

[15819 rows x 24149 columns]

In [120]:
vect = CountVectorizer(stop_words='english')

In [121]:
vect = CountVectorizer(ngram_range=(1, 2))

In [122]:
vect = CountVectorizer(max_df=0.3)

In [123]:
vect = CountVectorizer(min_df=1)

In [124]:
betterVect = CountVectorizer(stop_words='english',
                             min_df=1,
                             max_df=0.3,
                             ngram_range=(1, 1))

In [125]:
# labels
y = train['sentiment'] 

# features
X = xx
Xs = xxs

In [126]:
y

0        1
1        1
2        2
3        1
4        1
        ..
15814    1
15815    2
15816    0
15817   -1
15818    0
Name: sentiment, Length: 15819, dtype: int64

In [127]:
X

000  000058  00pm  01  02hjfphzix  02jbu2udyy  039strch8n  04  \
0        0       0     0   0           0           0           0   0   
1        0       0     0   0           0           0           0   0   
2        0       0     0   0           0           0           0   0   
3        0       0     0   0           0           0           0   0   
4        0       0     0   0           0           0           0   0   
...    ...     ...   ...  ..         ...         ...         ...  ..   
15814    0       0     0   0           0           0           0   0   
15815    0       0     0   0           0           0           0   0   
15816    0       0     0   0           0           0           0   0   
15817    0       0     0   0           0           0           0   0   
15818    0       0     0   0           0           0           0   0   

       04vmhuj4ko  060x2hcwm2  ...  ให  ไปรยาก  オゾン層  ㅤㅤㅤㅤㅤㅤglobal  ㅤㅤㅤㅤㅤㅤㅤㅤㅤ  \
0               0           0  ...   0       0     0             0          0   
1               0           0  ...   0       0     0             0          0   
2               0           0  ...   0       0     0             0          0   
3               0           0  ...   0       0     0             0          0   
4               0           0  ...   0       0     0             0          0   
...           ...         ...  ...  ..     ...   ...           ...        ...   
15814           0           0  ...   0       0     0             0          0   
15815           0           0  ...   0       0     0             0          0   
15816           0           0  ...   0       0     0             0          0   
15817           0           0  ...   0       0     0             0          0   
15818           0           0  ...   0       0     0             0          0   

       京都議定書  地球温暖化  温室効果  環境がテーマの文章ででやすい単語２  皮膚ガン  
0          0      0     0                  0     0  
1          0      0     0                  0     0  
2          0      0     0                  0     0  
3          0      0     0                  0     0  
4          0      0     0                  0     0  
...      ...    ...   ...                ...   ...  
15814      0      0     0                  0     0  
15815      0      0     0                  0     0  
15816      0      0     0                  0     0  
15817      0      0     0                  0     0  
15818      0      0     0                  0     0  

[15819 rows x 24149 columns]

In [128]:
X_transformed = pd.get_dummies(X, drop_first=True)
Xs_transformed = pd.get_dummies(Xs, drop_first=True)

In [129]:
from sklearn.model_selection import train_test_split

In [130]:
X_train, X_test, y_train, y_test = train_test_split(X_transformed, y, test_size=0.2, random_state=50)

In [131]:
from sklearn.linear_model import LogisticRegression

In [132]:
lr = LogisticRegression()

In [133]:
lr.fit(X_train, y_train)

C:\Users\5970\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [134]:
preds= lr.predict (X_test)

In [135]:
#pred_lm = l.predict(X_test)

In [136]:
from sklearn.metrics import confusion_matrix

In [137]:
confusion_matrix(y_test, preds)

array([[ 106,   35,   98,   15],
       [  24,  214,  177,   42],
       [  31,  113, 1465,  127],
       [   2,   24,  153,  538]], dtype=int64)

In [138]:
from sklearn.metrics import classification_report

In [139]:
print('Classification Report')
print(classification_report(y_test, preds, target_names=['0: aa', '1: bb', '2: cc', '3: dd']))

Classification Report
              precision    recall  f1-score   support

       0: aa       0.65      0.42      0.51       254
       1: bb       0.55      0.47      0.51       457
       2: cc       0.77      0.84      0.81      1736
       3: dd       0.75      0.75      0.75       717

    accuracy                           0.73      3164
   macro avg       0.68      0.62      0.64      3164
weighted avg       0.73      0.73      0.73      3164



In [140]:
lr.fit(X_train,y_train)
preds= lr.predict (X_test)


C:\Users\5970\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [141]:
predss= lr.predict (Xs_transformed)
daf = pd.DataFrame(test['tweetid'])
daf['sentiment']=predss
daf.head()


tweetid  sentiment
0   169760          1
1    35326          1
2   224985          1
3   476263          1
4   872928          0

## Fitting a simple model on training data and evaluate its performance

Fit a model on your cleaned data. Use `train_vec` as your features. Note that you need to convert `train_vec` to an array. 

You are familiar with this process, so there is less guidance here. You may also refer to train notebooks and the webinar pdf as guidance.

Your basic model should be a logistic regression, however if you try different models you will also perform the following procedure.

1. Split the training data into features and labels.
2. Split the training data further into training and validation data.
3. Fit the model on the training subset. 
4. Predict on the validation subset.
5. Calculate the performance metrics on the validation predictions.
6. Select a model based on validation performance (when you have more than one model).
8. Clean the test data.
9. Predict on the cleaned test data.
7. Write a csv that matches `sample_submission.csv`.
8. Submit to Kaggle.

In [142]:
# YOUR CODE HERE 





## Suggestions on how to improve the model - Extras 

Here are some ideas on how you can improve your model. Try some of them out once you have submitted your base model to Kaggle. Only use the methods you find improve your model performance.

 - Additional preprocessing 
     - Use some of the methods in the notebooks to balance the data
     - Replace links with the text `Link` to show the machine that there is a link present without the extraneous detail of the link text
     - Remove punctuation
     - Correct spelling
     - Bag of words vs. N-grams - which is better?
     - Try `TweetTokenizer()` - how does this differ from the tokenisers you are familiar with?
 - Consider which other models could do a better job (refer to course resources)
 - Consider some further feature engineering:
     - What other attributes of the tweets may be useful?
     - Should we perform feature selection given their size and sparseness of the vectorised tweets?
 - If you've mastered the above, try implementing hyperparameter tuning methods.
 - Compare all the models you try and remember to submit **the best one** based on test performance (f1-score using macro averaging). 
 
You may use the space below to try out these "Extras".

In [143]:
# Extras
# YOUR CODE HERE 




## How/why is the model bad?

Do you have any hypotheses as to how you can improve the model further? Use this space to investigate with mindful EDA if necessary.

In [144]:
# EDA
# YOUR CODE HERE 





Be sure to check whether each additional technique you apply actually improves your model performance.

## Submit your best model predictions 

Don't forget to submit your the predictions on the best model to Kaggle.

In [146]:
# write csv for best predictions
#output= pd.DataFrame ({"time":train['sentiment']})
submission2= daf
submission2.to_csv("submission2.csv", index=False)

